import {KeyCode, KeyboardCharacterLayout, type KeyConfig} from "@/utility/keyboard/keys.types";
import {
    ArrowBigUpDashIcon,
    ArrowBigUpIcon, ArrowDownIcon,
    ArrowLeftIcon, ArrowRightIcon,
    ArrowRightToLineIcon, ArrowUpIcon,
    CornerDownLeftIcon, SpaceIcon, SquareMenuIcon
} from "lucide-react";

export const KEY_MAPPING_QWERTY: Record<KeyCode, KeyConfig> = {
    [KeyCode.KeyA]: { code: KeyCode.KeyA, primaryKey: "a", shiftKey: "A", deadKeyVariants: {
            "´": { primaryKey: "á", shiftKey: "Á" },
            "`": { primaryKey: "à", shiftKey: "À" },
            "^": { primaryKey: "â", shiftKey: "Â" },
    }},
    [KeyCode.KeyB]: { code: KeyCode.KeyB, primaryKey: "b", shiftKey: "B" },
    [KeyCode.KeyC]: { code: KeyCode.KeyC, primaryKey: "c", shiftKey: "C" },
    [KeyCode.KeyD]: { code: KeyCode.KeyD, primaryKey: "d", shiftKey: "D" },
    [KeyCode.KeyE]: { code: KeyCode.KeyE, primaryKey: "e", shiftKey: "E", altGraphKey: "€", deadKeyVariants: {
            "´": { primaryKey: "é", shiftKey: "É" },
            "`": { primaryKey: "è", shiftKey: "È" },
            "^": { primaryKey: "ê", shiftKey: "Ê" },
        } },
    [KeyCode.KeyF]: { code: KeyCode.KeyF, primaryKey: "f", shiftKey: "F" },
    [KeyCode.KeyG]: { code: KeyCode.KeyG, primaryKey: "g", shiftKey: "G" },
    [KeyCode.KeyH]: { code: KeyCode.KeyH, primaryKey: "h", shiftKey: "H" },
    [KeyCode.KeyI]: { code: KeyCode.KeyI, primaryKey: "i", shiftKey: "I", deadKeyVariants: {
            "´": { primaryKey: "í", shiftKey: "Í" },
            "`": { primaryKey: "ì", shiftKey: "Ì" },
            "^": { primaryKey: "î", shiftKey: "Î" },
        } },
    [KeyCode.KeyJ]: { code: KeyCode.KeyJ, primaryKey: "j", shiftKey: "J" },
    [KeyCode.KeyK]: { code: KeyCode.KeyK, primaryKey: "k", shiftKey: "K" },
    [KeyCode.KeyL]: { code: KeyCode.KeyL, primaryKey: "l", shiftKey: "L" },
    // M + AltGr often does not produce µ, because other programs use this as a shortcut for mute
    [KeyCode.KeyM]: { code: KeyCode.KeyM, primaryKey: "m", shiftKey: "M", altGraphKey: "µ" },
    [KeyCode.KeyN]: { code: KeyCode.KeyN, primaryKey: "n", shiftKey: "N" },
    [KeyCode.KeyO]: { code: KeyCode.KeyO, primaryKey: "o", shiftKey: "O", deadKeyVariants: {
            "´": { primaryKey: "ó", shiftKey: "Ó" },
            "`": { primaryKey: "ò", shiftKey: "Ò" },
            "^": { primaryKey: "ô", shiftKey: "Ô" },
        } },
    [KeyCode.KeyP]: { code: KeyCode.KeyP, primaryKey: "p", shiftKey: "P" },
    [KeyCode.KeyQ]: { code: KeyCode.KeyQ, primaryKey: "q", shiftKey: "Q", altGraphKey: "@" },
    [KeyCode.KeyR]: { code: KeyCode.KeyR, primaryKey: "r", shiftKey: "R" },
    [KeyCode.KeyS]: { code: KeyCode.KeyS, primaryKey: "s", shiftKey: "S" },
    [KeyCode.KeyT]: { code: KeyCode.KeyT, primaryKey: "t", shiftKey: "T" },
    [KeyCode.KeyU]: { code: KeyCode.KeyU, primaryKey: "u", shiftKey: "U", deadKeyVariants: {
            "´": { primaryKey: "ú", shiftKey: "Ú" },
            "`": { primaryKey: "ù", shiftKey: "Ù" },
            "^": { primaryKey: "û", shiftKey: "Û" },
        } },
    [KeyCode.KeyV]: { code: KeyCode.KeyV, primaryKey: "v", shiftKey: "V" },
    [KeyCode.KeyW]: { code: KeyCode.KeyW, primaryKey: "w", shiftKey: "W" },
    [KeyCode.KeyX]: { code: KeyCode.KeyX, primaryKey: "x", shiftKey: "X" },
    [KeyCode.KeyY]: { code: KeyCode.KeyY, primaryKey: "y", shiftKey: "Y" },
    [KeyCode.KeyZ]: { code: KeyCode.KeyZ, primaryKey: "z", shiftKey: "Z" },

    // digits
    [KeyCode.Digit0]: { code: KeyCode.Digit0, primaryKey: "0", shiftKey: "=", altGraphKey: "}" },
    [KeyCode.Digit1]: { code: KeyCode.Digit1, primaryKey: "1", shiftKey: "!" },
    [KeyCode.Digit2]: { code: KeyCode.Digit2, primaryKey: "2", shiftKey: "\"", altGraphKey: "²" },
    [KeyCode.Digit3]: { code: KeyCode.Digit3, primaryKey: "3", shiftKey: "§", altGraphKey: "³" },
    [KeyCode.Digit4]: { code: KeyCode.Digit4, primaryKey: "4", shiftKey: "$" },
    [KeyCode.Digit5]: { code: KeyCode.Digit5, primaryKey: "5", shiftKey: "%" },
    [KeyCode.Digit6]: { code: KeyCode.Digit6, primaryKey: "6", shiftKey: "&" },
    [KeyCode.Digit7]: { code: KeyCode.Digit7, primaryKey: "7", shiftKey: "/", altGraphKey: "{" },
    [KeyCode.Digit8]: { code: KeyCode.Digit8, primaryKey: "8", shiftKey: "(", altGraphKey: "[" },
    [KeyCode.Digit9]: { code: KeyCode.Digit9, primaryKey: "9", shiftKey: ")", altGraphKey: "]" },

    // function keys
    [KeyCode.F1]: { code: KeyCode.F1, primaryKey: "F1" },
    [KeyCode.F2]: { code: KeyCode.F2, primaryKey: "F2" },
    [KeyCode.F3]: { code: KeyCode.F3, primaryKey: "F3" },
    [KeyCode.F4]: { code: KeyCode.F4, primaryKey: "F4" },
    [KeyCode.F5]: { code: KeyCode.F5, primaryKey: "F5" },
    [KeyCode.F6]: { code: KeyCode.F6, primaryKey: "F6" },
    [KeyCode.F7]: { code: KeyCode.F7, primaryKey: "F7" },
    [KeyCode.F8]: { code: KeyCode.F8, primaryKey: "F8" },
    [KeyCode.F9]: { code: KeyCode.F9, primaryKey: "F9" },
    [KeyCode.F10]: { code: KeyCode.F10, primaryKey: "F10" },
    [KeyCode.F11]: { code: KeyCode.F11, primaryKey: "F11" },
    [KeyCode.F12]: { code: KeyCode.F12, primaryKey: "F12" },
    [KeyCode.F13]: { code: KeyCode.F13, primaryKey: "F13" },
    [KeyCode.F14]: { code: KeyCode.F14, primaryKey: "F14" },
    [KeyCode.F15]: { code: KeyCode.F15, primaryKey: "F15" },
    [KeyCode.F16]: { code: KeyCode.F16, primaryKey: "F16" },
    [KeyCode.F17]: { code: KeyCode.F17, primaryKey: "F17" },
    [KeyCode.F18]: { code: KeyCode.F18, primaryKey: "F18" },
    [KeyCode.F19]: { code: KeyCode.F19, primaryKey: "F19" },
    [KeyCode.F20]: { code: KeyCode.F20, primaryKey: "F20" },
    [KeyCode.F21]: { code: KeyCode.F21, primaryKey: "F21" },
    [KeyCode.F22]: { code: KeyCode.F22, primaryKey: "F22" },
    [KeyCode.F23]: { code: KeyCode.F23, primaryKey: "F23" },
    [KeyCode.F24]: { code: KeyCode.F24, primaryKey: "F24" },

    // meta keys
    [KeyCode.Escape]: { code: KeyCode.Escape, primaryKey: "Esc" },
    [KeyCode.Space]: { code: KeyCode.Space, primaryKey: "Space", Icon: SpaceIcon },
    [KeyCode.ShiftLeft]: { code: KeyCode.ShiftLeft, primaryKey: "Shift", Icon: ArrowBigUpIcon },
    [KeyCode.ShiftRight]: { code: KeyCode.ShiftRight, primaryKey: "Shift", Icon: ArrowBigUpIcon },
    [KeyCode.ControlLeft]: { code: KeyCode.ControlLeft, primaryKey: "Strg" },
    [KeyCode.ControlRight]: { code: KeyCode.ControlRight, primaryKey: "Strg" },
    [KeyCode.AltLeft]: { code: KeyCode.AltLeft, primaryKey: "Alt" },
    [KeyCode.AltRight]: { code: KeyCode.AltRight, primaryKey: "Alt Gr" },
    [KeyCode.MetaLeft]: { code: KeyCode.MetaLeft, primaryKey: "Meta" },
    [KeyCode.MetaRight]: { code: KeyCode.MetaRight, primaryKey: "Meta" },
    [KeyCode.ContextMenu]: { code: KeyCode.ContextMenu, primaryKey: "Menu", Icon: SquareMenuIcon },
    [KeyCode.IntlBackslash]: { code: KeyCode.IntlBackslash, primaryKey: "<", shiftKey: ">", altGraphKey: "|" },
    [KeyCode.Fn]: { code: KeyCode.Fn, primaryKey: "Fn" },
    [KeyCode.Backquote]: { code: KeyCode.Backquote, primaryKey: "^", shiftKey: "°" },
    [KeyCode.Backslash]: { code: KeyCode.Backslash, primaryKey: "#", shiftKey: "'" },
    [KeyCode.Equal]: { code: KeyCode.Equal, primaryKey: "´", shiftKey: "`" },
    [KeyCode.Backspace]: { code: KeyCode.Backspace, primaryKey: "Backspace", Icon: ArrowLeftIcon },
    [KeyCode.Tab]: { code: KeyCode.Tab, primaryKey: "Tab", Icon: ArrowRightToLineIcon },
    [KeyCode.BracketLeft]: { code: KeyCode.BracketLeft, primaryKey: "ü", shiftKey: "Ü" },
    [KeyCode.BracketRight]: { code: KeyCode.BracketRight, primaryKey: "+", shiftKey: "*", altGraphKey: "~" },
    [KeyCode.Enter]: { code: KeyCode.Enter, primaryKey: "Enter", Icon: CornerDownLeftIcon },
    [KeyCode.CapsLock]: { code: KeyCode.CapsLock, primaryKey: "Caps Lock", Icon: ArrowBigUpDashIcon },
    [KeyCode.Semicolon]: { code: KeyCode.Semicolon, primaryKey: "ö", shiftKey: "Ö" },
    [KeyCode.Quote]: { code: KeyCode.Quote, primaryKey: "ä", shiftKey: "Ä" },
    [KeyCode.Comma]: { code: KeyCode.Comma, primaryKey: ",", shiftKey: ";" },
    [KeyCode.Period]: { code: KeyCode.Period, primaryKey: ".", shiftKey: ":" },
    [KeyCode.Slash]: { code: KeyCode.Slash, primaryKey: "-", shiftKey: "_" },
    [KeyCode.Command]: { code: KeyCode.Command, primaryKey: "Cmd" },
    [KeyCode.Minus]: { code: KeyCode.Minus, primaryKey: "ß", shiftKey: "?", altGraphKey: "\\" },

    // extra function keys
    [KeyCode.PrintScreen]: { code: KeyCode.PrintScreen, primaryKey: "Druck" },
    [KeyCode.ScrollLock]: { code: KeyCode.ScrollLock, primaryKey: "Rollen" },
    [KeyCode.Pause]: { code: KeyCode.Pause, primaryKey: "Pause" },
    [KeyCode.Insert]: { code: KeyCode.Insert, primaryKey: "Einfg" },
    [KeyCode.Delete]: { code: KeyCode.Delete, primaryKey: "Entf" },
    [KeyCode.Home]: { code: KeyCode.Home, primaryKey: "Pos1" },
    [KeyCode.End]: { code: KeyCode.End, primaryKey: "Ende" },
    [KeyCode.PageUp]: { code: KeyCode.PageUp, primaryKey: "Bild ↑" },
    [KeyCode.PageDown]: { code: KeyCode.PageDown, primaryKey: "Bild ↓" },

    // navigation keys
    [KeyCode.ArrowUp]: { code: KeyCode.ArrowUp, primaryKey: "↑", Icon: ArrowUpIcon },
    [KeyCode.ArrowDown]: { code: KeyCode.ArrowDown, primaryKey: "↓", Icon: ArrowDownIcon },
    [KeyCode.ArrowLeft]: { code: KeyCode.ArrowLeft, primaryKey: "←", Icon: ArrowLeftIcon },
    [KeyCode.ArrowRight]: { code: KeyCode.ArrowRight, primaryKey: "→", Icon: ArrowRightIcon },

    // numpad
    [KeyCode.NumLock]: { code: KeyCode.NumLock, primaryKey: "Num" },
    [KeyCode.Numpad0]: { code: KeyCode.Numpad0, primaryKey: "0" },
    [KeyCode.Numpad1]: { code: KeyCode.Numpad1, primaryKey: "1" },
    [KeyCode.Numpad2]: { code: KeyCode.Numpad2, primaryKey: "2" },
    [KeyCode.Numpad3]: { code: KeyCode.Numpad3, primaryKey: "3" },
    [KeyCode.Numpad4]: { code: KeyCode.Numpad4, primaryKey: "4" },
    [KeyCode.Numpad5]: { code: KeyCode.Numpad5, primaryKey: "5" },
    [KeyCode.Numpad6]: { code: KeyCode.Numpad6, primaryKey: "6" },
    [KeyCode.Numpad7]: { code: KeyCode.Numpad7, primaryKey: "7" },
    [KeyCode.Numpad8]: { code: KeyCode.Numpad8, primaryKey: "8" },
    [KeyCode.Numpad9]: { code: KeyCode.Numpad9, primaryKey: "9" },
    [KeyCode.NumpadDecimal]: { code: KeyCode.NumpadDecimal, primaryKey: "," },
    [KeyCode.NumpadAdd]: { code: KeyCode.NumpadAdd, primaryKey: "+" },
    [KeyCode.NumpadSubtract]: { code: KeyCode.NumpadSubtract, primaryKey: "-" },
    [KeyCode.NumpadMultiply]: { code: KeyCode.NumpadMultiply, primaryKey: "*" },
    [KeyCode.NumpadDivide]: { code: KeyCode.NumpadDivide, primaryKey: "/" },
    [KeyCode.NumpadEnter]: { code: KeyCode.NumpadEnter, primaryKey: "Enter" },
    [KeyCode.NumpadEqual]: { code: KeyCode.NumpadEqual, primaryKey: "=" },
    [KeyCode.NumpadComma]: { code: KeyCode.NumpadComma, primaryKey: "," },
    [KeyCode.NumpadParenLeft]: { code: KeyCode.NumpadParenLeft, primaryKey: "(" },
    [KeyCode.NumpadParenRight]: { code: KeyCode.NumpadParenRight, primaryKey: ")" },
    [KeyCode.NumpadBackspace]: { code: KeyCode.NumpadBackspace, primaryKey: "Backspace" },
    [KeyCode.NumpadClear]: { code: KeyCode.NumpadClear, primaryKey: "Clear" },
    [KeyCode.NumpadClearEntry]: { code: KeyCode.NumpadClearEntry, primaryKey: "CE" },

    // international / IME keys
    [KeyCode.IntlRo]: { code: KeyCode.IntlRo, primaryKey: "IntlRo" },
    [KeyCode.IntlYen]: { code: KeyCode.IntlYen, primaryKey: "¥" },
    [KeyCode.Convert]: { code: KeyCode.Convert, primaryKey: "変換" },
    [KeyCode.NonConvert]: { code: KeyCode.NonConvert, primaryKey: "無変換" },
    [KeyCode.KanaMode]: { code: KeyCode.KanaMode, primaryKey: "カナ" },
    [KeyCode.Lang1]: { code: KeyCode.Lang1, primaryKey: "Lang1" },
    [KeyCode.Lang2]: { code: KeyCode.Lang2, primaryKey: "Lang2" },
    [KeyCode.Lang3]: { code: KeyCode.Lang3, primaryKey: "Lang3" },
    [KeyCode.Lang4]: { code: KeyCode.Lang4, primaryKey: "Lang4" },
    [KeyCode.Lang5]: { code: KeyCode.Lang5, primaryKey: "Lang5" },

    // system / power keys
    [KeyCode.Power]: { code: KeyCode.Power, primaryKey: "Power" },
    [KeyCode.Sleep]: { code: KeyCode.Sleep, primaryKey: "Sleep" },
    [KeyCode.WakeUp]: { code: KeyCode.WakeUp, primaryKey: "Wake" },
    [KeyCode.Eject]: { code: KeyCode.Eject, primaryKey: "Eject" },
    [KeyCode.Help]: { code: KeyCode.Help, primaryKey: "Help" },

    // legacy editing keys
    [KeyCode.Again]: { code: KeyCode.Again, primaryKey: "Again" },
    [KeyCode.Undo]: { code: KeyCode.Undo, primaryKey: "Undo" },
    [KeyCode.Cut]: { code: KeyCode.Cut, primaryKey: "Cut" },
    [KeyCode.Copy]: { code: KeyCode.Copy, primaryKey: "Copy" },
    [KeyCode.Paste]: { code: KeyCode.Paste, primaryKey: "Paste" },
    [KeyCode.Find]: { code: KeyCode.Find, primaryKey: "Find" },
    [KeyCode.Open]: { code: KeyCode.Open, primaryKey: "Open" },
    [KeyCode.Props]: { code: KeyCode.Props, primaryKey: "Props" },
    [KeyCode.Select]: { code: KeyCode.Select, primaryKey: "Select" },

    // media keys
    [KeyCode.MediaPlayPause]: { code: KeyCode.MediaPlayPause, primaryKey: "Play/Pause" },
    [KeyCode.MediaStop]: { code: KeyCode.MediaStop, primaryKey: "Stop" },
    [KeyCode.MediaTrackNext]: { code: KeyCode.MediaTrackNext, primaryKey: "Next" },
    [KeyCode.MediaTrackPrevious]: { code: KeyCode.MediaTrackPrevious, primaryKey: "Prev" },
    [KeyCode.MediaSelect]: { code: KeyCode.MediaSelect, primaryKey: "Media" },
    [KeyCode.LaunchMediaPlayer]: { code: KeyCode.LaunchMediaPlayer, primaryKey: "Media Player" },
    [KeyCode.AudioVolumeUp]: { code: KeyCode.AudioVolumeUp, primaryKey: "Vol +" },
    [KeyCode.AudioVolumeDown]: { code: KeyCode.AudioVolumeDown, primaryKey: "Vol -" },
    [KeyCode.AudioVolumeMute]: { code: KeyCode.AudioVolumeMute, primaryKey: "Mute" },

    // browser / app launch keys
    [KeyCode.BrowserBack]: { code: KeyCode.BrowserBack, primaryKey: "Back" },
    [KeyCode.BrowserForward]: { code: KeyCode.BrowserForward, primaryKey: "Forward" },
    [KeyCode.BrowserRefresh]: { code: KeyCode.BrowserRefresh, primaryKey: "Refresh" },
    [KeyCode.BrowserStop]: { code: KeyCode.BrowserStop, primaryKey: "Stop" },
    [KeyCode.BrowserSearch]: { code: KeyCode.BrowserSearch, primaryKey: "Search" },
    [KeyCode.BrowserFavorites]: { code: KeyCode.BrowserFavorites, primaryKey: "Favorites" },
    [KeyCode.BrowserHome]: { code: KeyCode.BrowserHome, primaryKey: "Home" },
    [KeyCode.LaunchApp1]: { code: KeyCode.LaunchApp1, primaryKey: "App1" },
    [KeyCode.LaunchApp2]: { code: KeyCode.LaunchApp2, primaryKey: "App2" },
    [KeyCode.LaunchMail]: { code: KeyCode.LaunchMail, primaryKey: "Mail" },
};

export const KEY_MAPPING_QWERTZ: Record<KeyCode, KeyConfig> = {
    ...KEY_MAPPING_QWERTY,
    [KeyCode.KeyY]: { code: KeyCode.KeyY, primaryKey: "z", shiftKey: "Z" },
    [KeyCode.KeyZ]: { code: KeyCode.KeyZ, primaryKey: "y", shiftKey: "Y" },
};

export const KEY_MAPPING_AZERTY: Record<KeyCode, KeyConfig> = {
    ...KEY_MAPPING_QWERTY,

    // letter position swaps
    [KeyCode.KeyQ]: { code: KeyCode.KeyQ, primaryKey: "a", shiftKey: "A" },
    [KeyCode.KeyW]: { code: KeyCode.KeyW, primaryKey: "z", shiftKey: "Z" },
    [KeyCode.KeyA]: { code: KeyCode.KeyA, primaryKey: "q", shiftKey: "Q" },
    [KeyCode.KeyZ]: { code: KeyCode.KeyZ, primaryKey: "w", shiftKey: "W" },
    [KeyCode.KeyM]: { code: KeyCode.KeyM, primaryKey: ",", shiftKey: "?" },

    // punctuation keys that shift with the M move
    [KeyCode.Semicolon]: { code: KeyCode.Semicolon, primaryKey: "m", shiftKey: "M" },
    [KeyCode.Comma]: { code: KeyCode.Comma, primaryKey: ";", shiftKey: "." },
    [KeyCode.Period]: { code: KeyCode.Period, primaryKey: ":", shiftKey: "/" },
    [KeyCode.Slash]: { code: KeyCode.Slash, primaryKey: "!", shiftKey: "§" },

    // digit row (unshifted = symbol, shifted = digit)
    [KeyCode.Digit0]: { code: KeyCode.Digit0, primaryKey: "à", shiftKey: "0", altGraphKey: "@" },
    [KeyCode.Digit1]: { code: KeyCode.Digit1, primaryKey: "&", shiftKey: "1" },
    [KeyCode.Digit2]: { code: KeyCode.Digit2, primaryKey: "é", shiftKey: "2", altGraphKey: "~" },
    [KeyCode.Digit3]: { code: KeyCode.Digit3, primaryKey: "\"", shiftKey: "3", altGraphKey: "#" },
    [KeyCode.Digit4]: { code: KeyCode.Digit4, primaryKey: "'", shiftKey: "4", altGraphKey: "{" },
    [KeyCode.Digit5]: { code: KeyCode.Digit5, primaryKey: "(", shiftKey: "5", altGraphKey: "[" },
    [KeyCode.Digit6]: { code: KeyCode.Digit6, primaryKey: "-", shiftKey: "6", altGraphKey: "|" },
    [KeyCode.Digit7]: { code: KeyCode.Digit7, primaryKey: "è", shiftKey: "7", altGraphKey: "`" },
    [KeyCode.Digit8]: { code: KeyCode.Digit8, primaryKey: "_", shiftKey: "8", altGraphKey: "\\" },
    [KeyCode.Digit9]: { code: KeyCode.Digit9, primaryKey: "ç", shiftKey: "9", altGraphKey: "^" },

    // symbol keys around the digit row / right of L / ISO extra key
    [KeyCode.Minus]: { code: KeyCode.Minus, primaryKey: ")", shiftKey: "°", altGraphKey: "]" },
    [KeyCode.Equal]: { code: KeyCode.Equal, primaryKey: "=", shiftKey: "+", altGraphKey: "}" },
    [KeyCode.BracketLeft]: { code: KeyCode.BracketLeft, primaryKey: "^", shiftKey: "¨" },
    [KeyCode.BracketRight]: { code: KeyCode.BracketRight, primaryKey: "$", shiftKey: "£", altGraphKey: "¤" },
    [KeyCode.Backslash]: { code: KeyCode.Backslash, primaryKey: "*", shiftKey: "µ" },
    [KeyCode.IntlBackslash]: { code: KeyCode.IntlBackslash, primaryKey: "<", shiftKey: ">", altGraphKey: "|" },
    [KeyCode.Backquote]: { code: KeyCode.Backquote, primaryKey: "²" },
    [KeyCode.Quote]: { code: KeyCode.Quote, primaryKey: "ù", shiftKey: "%" },
};


export const KEY_MAPPING: Record<KeyboardCharacterLayout, Record<KeyCode, KeyConfig>> = {
    [KeyboardCharacterLayout.Qwerty]: KEY_MAPPING_QWERTY,
    [KeyboardCharacterLayout.Qwertz]: KEY_MAPPING_QWERTZ,
    [KeyboardCharacterLayout.Azerty]: KEY_MAPPING_AZERTY,
}