import {KEY_CONFIG, KeyboardCharacterLayout, type KeyConfig} from "@/utility/keys";

export const KEYBOARD_FUNCTION_KEYS: KeyConfig[][] = [
    [KEY_CONFIG.Escape],
    [KEY_CONFIG.F1, KEY_CONFIG.F2, KEY_CONFIG.F3, KEY_CONFIG.F4],
    [KEY_CONFIG.F5, KEY_CONFIG.F6, KEY_CONFIG.F7, KEY_CONFIG.F8],
    [KEY_CONFIG.F9, KEY_CONFIG.F10, KEY_CONFIG.F11, KEY_CONFIG.F12],
] as const;

export const KEYBOARD_SYSTEM_KEYS: KeyConfig[]  = [
    KEY_CONFIG.PrintScreen, KEY_CONFIG.ScrollLock, KEY_CONFIG.Pause
] as const;

export const KEYBOARD_EDITING_KEYS: KeyConfig[]  = [
    KEY_CONFIG.Insert, KEY_CONFIG.Home, KEY_CONFIG.PageUp,
    KEY_CONFIG.Delete, KEY_CONFIG.End, KEY_CONFIG.PageDown
] as const;

export const KEYBOARD_ARROW_KEYS: KeyConfig[]  = [
    KEY_CONFIG.ArrowUp, KEY_CONFIG.ArrowLeft, KEY_CONFIG.ArrowDown, KEY_CONFIG.ArrowRight,
] as const;

export const KEYBOARD_NUMPAD: KeyConfig[] = [
    KEY_CONFIG.NumLock, KEY_CONFIG.NumpadDivide, KEY_CONFIG.NumpadMultiply, KEY_CONFIG.NumpadSubtract,
    KEY_CONFIG.Numpad7, KEY_CONFIG.Numpad8, KEY_CONFIG.Numpad9, KEY_CONFIG.NumpadAdd,
    KEY_CONFIG.Numpad4, KEY_CONFIG.Numpad5, KEY_CONFIG.Numpad6,
    KEY_CONFIG.Numpad1, KEY_CONFIG.Numpad2, KEY_CONFIG.Numpad3, KEY_CONFIG.NumpadEnter,
    KEY_CONFIG.Numpad0, KEY_CONFIG.NumpadDecimal,
] as const;

export const KEYBOARD_ALPHANUMERIC_QWERTZ: KeyConfig[][] = [
    [KEY_CONFIG.Backquote, KEY_CONFIG.Digit1, KEY_CONFIG.Digit2, KEY_CONFIG.Digit3, KEY_CONFIG.Digit4, KEY_CONFIG.Digit5, KEY_CONFIG.Digit6, KEY_CONFIG.Digit7, KEY_CONFIG.Digit8, KEY_CONFIG.Digit9, KEY_CONFIG.Digit0, KEY_CONFIG.Minus, KEY_CONFIG.Equal, KEY_CONFIG.Backspace],
    [KEY_CONFIG.Tab, KEY_CONFIG.KeyQ, KEY_CONFIG.KeyW, KEY_CONFIG.KeyE, KEY_CONFIG.KeyR, KEY_CONFIG.KeyT, KEY_CONFIG.KeyZ, KEY_CONFIG.KeyU, KEY_CONFIG.KeyI, KEY_CONFIG.KeyO, KEY_CONFIG.KeyP, KEY_CONFIG.BracketLeft, KEY_CONFIG.BracketRight, KEY_CONFIG.Enter],
    [KEY_CONFIG.CapsLock, KEY_CONFIG.KeyA, KEY_CONFIG.KeyS, KEY_CONFIG.KeyD, KEY_CONFIG.KeyF, KEY_CONFIG.KeyG, KEY_CONFIG.KeyH, KEY_CONFIG.KeyJ, KEY_CONFIG.KeyK, KEY_CONFIG.KeyL, KEY_CONFIG.Semicolon, KEY_CONFIG.Quote, KEY_CONFIG.Backslash],
    [KEY_CONFIG.ShiftLeft, KEY_CONFIG.IntlBackslash, KEY_CONFIG.KeyY, KEY_CONFIG.KeyX, KEY_CONFIG.KeyC, KEY_CONFIG.KeyV, KEY_CONFIG.KeyB, KEY_CONFIG.KeyN, KEY_CONFIG.KeyM, KEY_CONFIG.Comma, KEY_CONFIG.Period, KEY_CONFIG.Slash, KEY_CONFIG.ShiftRight],
    [KEY_CONFIG.ControlLeft, KEY_CONFIG.MetaLeft, KEY_CONFIG.AltLeft, KEY_CONFIG.Space, KEY_CONFIG.AltRight, KEY_CONFIG.Fn, KEY_CONFIG.ContextMenu, KEY_CONFIG.ControlRight],
] as const;

export const KEYBOARD_ALPHANUMERIC_QWERTY: KeyConfig[][] = [
    [KEY_CONFIG.Backquote, KEY_CONFIG.Digit1, KEY_CONFIG.Digit2, KEY_CONFIG.Digit3, KEY_CONFIG.Digit4, KEY_CONFIG.Digit5, KEY_CONFIG.Digit6, KEY_CONFIG.Digit7, KEY_CONFIG.Digit8, KEY_CONFIG.Digit9, KEY_CONFIG.Digit0, KEY_CONFIG.Minus, KEY_CONFIG.Equal, KEY_CONFIG.Backspace],
    [KEY_CONFIG.Tab, KEY_CONFIG.KeyQ, KEY_CONFIG.KeyW, KEY_CONFIG.KeyE, KEY_CONFIG.KeyR, KEY_CONFIG.KeyT, KEY_CONFIG.KeyY, KEY_CONFIG.KeyU, KEY_CONFIG.KeyI, KEY_CONFIG.KeyO, KEY_CONFIG.KeyP, KEY_CONFIG.BracketLeft, KEY_CONFIG.BracketRight, KEY_CONFIG.Enter],
    [KEY_CONFIG.CapsLock, KEY_CONFIG.KeyA, KEY_CONFIG.KeyS, KEY_CONFIG.KeyD, KEY_CONFIG.KeyF, KEY_CONFIG.KeyG, KEY_CONFIG.KeyH, KEY_CONFIG.KeyJ, KEY_CONFIG.KeyK, KEY_CONFIG.KeyL, KEY_CONFIG.Semicolon, KEY_CONFIG.Quote, KEY_CONFIG.Backslash],
    [KEY_CONFIG.ShiftLeft, KEY_CONFIG.IntlBackslash, KEY_CONFIG.KeyZ, KEY_CONFIG.KeyX, KEY_CONFIG.KeyC, KEY_CONFIG.KeyV, KEY_CONFIG.KeyB, KEY_CONFIG.KeyN, KEY_CONFIG.KeyM, KEY_CONFIG.Comma, KEY_CONFIG.Period, KEY_CONFIG.Slash, KEY_CONFIG.ShiftRight],
    [KEY_CONFIG.ControlLeft, KEY_CONFIG.MetaLeft, KEY_CONFIG.AltLeft, KEY_CONFIG.Space, KEY_CONFIG.AltRight, KEY_CONFIG.Fn, KEY_CONFIG.ContextMenu, KEY_CONFIG.ControlRight],
] as const;

export const KEYBOARD_ALPHANUMERIC_KEYS: Record<KeyboardCharacterLayout, KeyConfig[][]> = {
    qwerty: KEYBOARD_ALPHANUMERIC_QWERTY,
    qwertz: KEYBOARD_ALPHANUMERIC_QWERTZ,
    azerty: [[]],
} as const;